### ISSUE TITLE
Landing: Become a mentor section

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#10]
Landing page contains a section for becoming a mentor:

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/34896733/6559137e-7781-4390-99a9-6020e996f260)

Takes in title, description, cta (text and link within application) and image
- [image source link](https://drive.google.com/file/d/1oGo8MPICFlt60KrIOLGKLisahwZI2HUq/view?usp=drive_link)

### MOBILE

Use square image on small mobile (breakpoint smaller than 'sm')
- [image source link](https://drive.google.com/file/d/129T7I_CNz1pUvH_8WBqzbpHXUTU955aV/view?usp=drive_link)

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/26842896/5c3d0975-bc89-46cc-9436-f9535b1252fa)

MUI default breakpoints [Documentation link:](https://mui.com/material-ui/customization/breakpoints/)
- xs, extra-small: 0px
- sm, small: 600px
- md, medium: 900px
- lg, large: 1200px
- xl, extra-large: 1536px

**Comment by lilyndk** [comment]
Hi @jpmaHub 

I've added this ['yellow note' in Figma](https://www.figma.com/design/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-UI-Designs?node-id=57242-34351&t=AKTfST8JGn0GPHSm-4) to note the mappings of elements to the MUI ‘styling color and typography variables’. If we use those variables, the styles should closely align with the Figma designs once we add update the theme colors and typography styles (which I’m still working on defining).

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/26842896/46070990-1d9f-4fc0-9555-dfb92e0e5b8a)
