### ISSUE TITLE
Jest Setup

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#15]
Jest package and NextJS is causing issues when testing next js internal router
This needs to be addressed
no normal test should be affected, if the component is not using `withRouter` (as the header does)

**Comment by stepsen89** [comment]
accidentally deleted the wrong issue, this one was meant to be assigned 🙈

**Comment by adeola2310** [comment]
@stepsen89 would you love to review this : https://github.com/Women-Coding-Community/wcc-frontend/pull/23
