### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#24]
Footer contains the gradial border on top

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/34896733/c12b88b2-7767-4197-b046-3657a6f32c8e)

**Comment by lilyndk** [comment]
Hi @stepsen89 , attached is the footer slack icon:

![Image](https://github.com/user-attachments/assets/3c16f077-a140-4787-a150-bb48b26cfc9d)
