### ISSUE TITLE
Landing: Hero Component

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#5]
Landing Page contains a hero component:

Review with design if reusability could be extended to also be able to be used for hero components with inverted sections (e.g. book-club) see https://www.figma.com/design/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-UI-Designs?node-id=47909-2&t=4JC742BVuAwIdbiL-0

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/34896733/95e81a78-a5aa-469c-95e2-27717409c2b8)

taking in Title, subtitle and image (depends on view: mobile, tablet, phone)

**Comment by lilyndk** [comment]
Hi @MitaliShah,
 
I've added this ['yellow note' in Figma](https://www.figma.com/design/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-UI-Designs?node-id=57222-34264&t=AKTfST8JGn0GPHSm-4) to map the hero component elements to the MUI ‘styling color and typography variables’. If we use those variables, the styles should closely align with the Figma designs once we add update the theme colors and typography styles (which I’m still working on defining).

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/26842896/d47eba5a-a35c-455f-8087-2a6627d0be3b)

**Comment by lilyndk** [comment]
Since the hero border uses the same gradient styles as the footer gradient, we might want to consider creating a reusable 'gradient border' variable for that.
