### ISSUE TITLE
Landing: Events: Event Card

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#6]
Landing section of events displays cards with

Label (e.g. book-club)
Event Date
Title of event
host(s)/ speaker
description
link to external page (for now external)
image

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/34896733/81b1c49b-16c8-4350-b4bc-3a6b71c2963f)

**Comment by lilyndk** [comment]
Regarding the 'featured event' cards background color system, the colors in the designs are defined by the 'event category label'. And based on the existing past events list (https://womencodingcommunity.com/events), we are using these category tags:
- Book club
- Career talk
- Tech talk
- Writing club

@dricazenck Which event categories do we currently know we will need? This list will also be used as filtering options on the event search page.

**Comment by dricazenck** [comment]
> are using these category

All programms will be topics, for now we have these: 

  MENTORSHIP,
  STUDY_GROUPS,
  WEBSITE,
  READING_CLUB,
  WRITE_CLUB,
  CODING_CLUB,
  SYSTEM_DESIGN,
  CV_CLINIC,
  MOCKING_INTERVIEW,
  MACHINE_LEARNING,
  QA_TRACK,
  DEVOPS_TRACK,
  JAVA_TRACK,
  FRONTEND_TRACK,
  LEETCODE_STUDY,
  PLATFORM
