### ISSUE TITLE
Landing: Opportunities and Programmes: Section

### ISSUE THREAD

**Issue by stepsen89** [Women-Coding-Community/wcc-frontend#9]
Landing page contains opportunities and programmes section: containing title, description and a map over the tiles we want to display.

Icons can be mapped within FE application

![Image](https://github.com/Women-Coding-Community/wcc-frontend/assets/26842896/2e083a60-c19a-4d92-a09c-6c9bb052e9d9)

**Comment by lilyndk** [comment]
This is the list of the icons used from [Google's Material Symbols font icons library](https://fonts.google.com/icons):

1. Mentorship Material icon name/link:[ ‘Diversity2’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:diversity_2:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=diversity&icon.size=24&icon.color=%23e8eaed)
2. Events Material icon name/link:[ ‘Calendar Month’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:calendar_month:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=Calendar&icon.size=24&icon.color=%23e8eaed)
3. Book club Material icon name/link: [‘Book 2’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:book_2:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=book&icon.size=24&icon.color=%23e8eaed)
4. CV Material icon name/link: [‘Work’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:work:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=job&icon.size=24&icon.color=%23e8eaed)
5. Mock Interviews Material icon name/link: [‘Group’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:group:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=grou&icon.size=24&icon.color=%23e8eaed)
6. Leetcode Material icon name/link: [‘Code Blocks’](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:code_blocks:FILL@0;wght@200;GRAD@0;opsz@24&icon.query=code&icon.size=24&icon.color=%23e8eaed)

**Comment by stepsen89** [comment]
Hi @lilyndk 

We would need the icon name like diversity_2 (defined at the bottom of the icon description on Google Font) - but I believe that is defined in the backend

**Comment by lilyndk** [comment]
Hi @joanaBrit 

I've added this ['yellow note' in Figma](https://www.figma.com/design/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-UI-Designs?node-id=57228-34342&t=AKTfST8JGn0GPHSm-4) to note the mappings of the component elements to the MUI ‘styling color and typography variables’. If we use those variables, the styles should closely align with the Figma designs once we add update the theme colors and typography styles (which I’m still working on defining).

**Comment by lilyndk** [comment]
We probably want to make the 'gradient background' style reusable, since it's  also used on the ['Celebrate Her' page](https://www.figma.com/design/ncdevYZK7NGuTK3hc6mP4e/WCC-Platform-Material-UI-Designs?node-id=56284-31510&t=AKTfST8JGn0GPHSm-4) for example.

**Comment by joanaBrit** [comment]
Hi @lilyndk I made a component for the gradient background, making it reusable. I think the styling is done, but let's see if it's okay when you guys check it. Just missing the tests to make, I will study and write them.
